//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMutation
    {
        public int Id { get; set; }
        public string ItemId { get; set; }
        public int Quantity { get; set; }
        public int MutationCase { get; set; }
        public int ItemCase { get; set; }
        public int SourceDocumentId { get; set; }
        public string SourceDocument { get; set; }
        public int SourceDocumentDetailId { get; set; }
        public string SourceDocumentDetail { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    }
}
